### PR TITLE
responsiveness

### PR DESCRIPTION
**Pull request by nenadjaja**
Here is my solution for responsiveness:
1. When you first land on the Details page, only the Query editor page is shown
2. When you click on the Play button, it replaces that pane with the Result pane
3. If you want to go back to the Query editor, simply click on the "Query" button in the top left
4. If you want to see the schema, click on Show Schema and it will be shown full width

I think it makes for a nice responsive experience. I also tried to add some animations, but it wasn't successful. I can look into that tomorrow. 

Resolves https://github.com/graphprotocol/graph-explorer/issues/283

### CODE REVIEW

**Comment by Jannis** [comment]
@nenadjaja Could you record a short video or post a few screenshoots of what this looks like in action? I can't easily test it right now.

**Comment by nenadjaja** [comment]
@Jannis yep sure. Here it is: 
Chrome: https://drive.google.com/open?id=1HDMRQY5cvg5b-IMVKbfcyy__kuhxev0H
Safari: https://drive.google.com/open?id=1O1DY2IpRWKYJoRSCsfHTG86vJdF-Adxf

I think it looks nice on the simulator. But let's see how it looks like on actual phones :)

**Comment by Jannis** [comment]
@nenadjaja Great! What happens when you make a row in the query editor so long that horizontal scrolling is introduced? Does the query then overlap with the line numbers?

**Comment by Jannis** [comment]
If it does, we can still fix that in a separate PR. This looks much, much better than what's currently in production.

**Review by Jannis — APPROVED** [review]

**Comment by nenadjaja** [comment]
@Jannis Good question. It goes under the numbers on the left, and it's hard to read. I'll try to make it so it goes on top of the numbers, so the numbers basically disappear underneath if you scroll to the left, and show up once you scroll to the right. Hopefully I am not adding 1 more day of work with this haha :)

**Comment by nenadjaja** [comment]
Fixed! It ended up being a really small fix

**Pull request merged**
